import { resolvePublicUrl } from "../utils/publicUrl";

export const APP_CONFIG = {
  exhibition: {
    width: 3.0,
    height: 2.0,
    wallOffset: 0.02,
    maxDepthOffset: 0.28,
  },
  scale: {
    min: 0.75,
    max: 1.3,
  },
  textSpeed: {
    min: 0.08,
    max: 0.35,
  },
  layout: {
    padding: 0.025,
    collisionPadding: 0.006,
    maxPlacementAttempts: 100,
    fallbackGridStep: 0.035,
    globalSeed: 202607,
    textLaneCount: 6,
    textLineHeight: 0.065,
    textVerticalPadding: 0.065,
    textPanelMaxHeight: 0.8,
    textPanelMinWidth: 1.05,
    textPanelMaxWidth: 6.4,
    textCharacterWidth: 0.042,
    textHorizontalPadding: 0.1,
    mediaBaseSize: 0.28,
    mediaMaxWidth: 0.64,
    mediaMaxHeight: 0.54,
    mediaSizeVariationMin: 0.68,
    mediaSizeVariationMax: 1.38,
    clusterBias: 0.2,
    mediaTiltDegrees: {
      x: 3,
      y: 5,
      z: 3,
    },
    textTiltDegrees: {
      x: 1.5,
      y: 2.5,
      z: 1.5,
    },
    mediaMountDepthMin: 0.022,
    mediaMountDepthMax: 0.068,
    textMountDepthMin: 0.008,
    textMountDepthMax: 0.018,
    frameMargin: 0.015,
    captionHeight: 0.065,
  },
  performance: {
    maxPosts: 90,
    maxActiveVideos: 1,
    preloadConcurrency: 4,
    maxPixelRatio: 1.5,
    antialiasMaxPixelRatio: 1.5,
    recommendedMaxImageDimension: 2_048,
  },
  data: {
    postsUrl: resolvePublicUrl("/data/posts.json"),
    placeholderPostsUrl: resolvePublicUrl("/data/posts.placeholder.json"),
    customPostsUrl: resolvePublicUrl("/data/posts.custom.json"),
    defaultAuthorIconSrc: resolvePublicUrl("/assets/placeholders/author.svg"),
    imagePlaceholderSrc: resolvePublicUrl("/assets/posts/image-placeholder.svg"),
    videoPlaceholderSrc: resolvePublicUrl("/assets/posts/video-placeholder.svg"),
  },
  preview: {
    cameraFov: 45,
    cameraNear: 0.1,
    cameraFar: 100,
    cameraDistance: 2.2,
  },
  ar: {
    wallOffset: 0.025,
    cameraNear: 0.01,
    cameraFar: 100,
  },
  fallback: {
    cameraDistance: 2.0,
    defaultScale: 1.1,
    minScale: 0.65,
    maxScale: 2.2,
    maxPositionX: 4,
    maxPositionY: 3,
    dragWorldWidth: 4,
    dragWorldHeight: 4,
  },
  routing: {
    modeParameter: "mode",
    previewValue: "preview",
    dataParameter: "data",
    placeholderDataValue: "placeholder",
    sampleDataValue: "sample",
    customDataValue: "custom",
  },
} as const;
